# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models import rule_pb2 as models_dot_rule__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='models/payload.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14models/payload.proto\x1a\x11models/rule.proto\"\xc8\x02\n\x12TransactionPayload\x12\x35\n\x0cpayload_type\x18\x01 \x01(\x0e\x32\x1f.TransactionPayload.PayloadType\x12&\n\x0e\x63reate_account\x18\x02 \x01(\x0b\x32\x0e.CreateAccount\x12\"\n\x0c\x63reate_asset\x18\x03 \x01(\x0b\x32\x0c.CreateAsset\x12$\n\rapprove_asset\x18\x04 \x01(\x0b\x32\r.ApproveAsset\x12 \n\x0b\x63lose_asset\x18\x05 \x01(\x0b\x32\x0b.CloseAsset\"g\n\x0bPayloadType\x12\x0e\n\nTYPE_UNSET\x10\x00\x12\x12\n\x0e\x43REATE_ACCOUNT\x10\x02\x12\x10\n\x0c\x43REATE_ASSET\x10\x03\x12\x11\n\rAPPROVE_ASSET\x10\x04\x12\x0f\n\x0b\x43LOSE_ASSET\x10\x05\"J\n\rCreateAccount\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x16\n\x0e\x61pprover_level\x18\x03 \x01(\r\"Y\n\x0b\x43reateAsset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tnum_steps\x18\x03 \x01(\r\x12\x14\n\x05rules\x18\x04 \x03(\x0b\x32\x05.Rule\"3\n\x0c\x41pproveAsset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rapproval_step\x18\x03 \x01(\t\"\x1a\n\nCloseAsset\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')
  ,
  dependencies=[models_dot_rule__pb2.DESCRIPTOR,])



_TRANSACTIONPAYLOAD_PAYLOADTYPE = _descriptor.EnumDescriptor(
  name='PayloadType',
  full_name='TransactionPayload.PayloadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ACCOUNT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ASSET', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPROVE_ASSET', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_ASSET', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=269,
  serialized_end=372,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTIONPAYLOAD_PAYLOADTYPE)


_TRANSACTIONPAYLOAD = _descriptor.Descriptor(
  name='TransactionPayload',
  full_name='TransactionPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_type', full_name='TransactionPayload.payload_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_account', full_name='TransactionPayload.create_account', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_asset', full_name='TransactionPayload.create_asset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='approve_asset', full_name='TransactionPayload.approve_asset', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='close_asset', full_name='TransactionPayload.close_asset', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSACTIONPAYLOAD_PAYLOADTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=372,
)


_CREATEACCOUNT = _descriptor.Descriptor(
  name='CreateAccount',
  full_name='CreateAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateAccount.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='CreateAccount.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='approver_level', full_name='CreateAccount.approver_level', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=448,
)


_CREATEASSET = _descriptor.Descriptor(
  name='CreateAsset',
  full_name='CreateAsset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateAsset.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='CreateAsset.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_steps', full_name='CreateAsset.num_steps', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rules', full_name='CreateAsset.rules', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=539,
)


_APPROVEASSET = _descriptor.Descriptor(
  name='ApproveAsset',
  full_name='ApproveAsset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ApproveAsset.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='approval_step', full_name='ApproveAsset.approval_step', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=592,
)


_CLOSEASSET = _descriptor.Descriptor(
  name='CloseAsset',
  full_name='CloseAsset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CloseAsset.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=594,
  serialized_end=620,
)

_TRANSACTIONPAYLOAD.fields_by_name['payload_type'].enum_type = _TRANSACTIONPAYLOAD_PAYLOADTYPE
_TRANSACTIONPAYLOAD.fields_by_name['create_account'].message_type = _CREATEACCOUNT
_TRANSACTIONPAYLOAD.fields_by_name['create_asset'].message_type = _CREATEASSET
_TRANSACTIONPAYLOAD.fields_by_name['approve_asset'].message_type = _APPROVEASSET
_TRANSACTIONPAYLOAD.fields_by_name['close_asset'].message_type = _CLOSEASSET
_TRANSACTIONPAYLOAD_PAYLOADTYPE.containing_type = _TRANSACTIONPAYLOAD
_CREATEASSET.fields_by_name['rules'].message_type = models_dot_rule__pb2._RULE
DESCRIPTOR.message_types_by_name['TransactionPayload'] = _TRANSACTIONPAYLOAD
DESCRIPTOR.message_types_by_name['CreateAccount'] = _CREATEACCOUNT
DESCRIPTOR.message_types_by_name['CreateAsset'] = _CREATEASSET
DESCRIPTOR.message_types_by_name['ApproveAsset'] = _APPROVEASSET
DESCRIPTOR.message_types_by_name['CloseAsset'] = _CLOSEASSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionPayload = _reflection.GeneratedProtocolMessageType('TransactionPayload', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONPAYLOAD,
  __module__ = 'models.payload_pb2'
  # @@protoc_insertion_point(class_scope:TransactionPayload)
  ))
_sym_db.RegisterMessage(TransactionPayload)

CreateAccount = _reflection.GeneratedProtocolMessageType('CreateAccount', (_message.Message,), dict(
  DESCRIPTOR = _CREATEACCOUNT,
  __module__ = 'models.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateAccount)
  ))
_sym_db.RegisterMessage(CreateAccount)

CreateAsset = _reflection.GeneratedProtocolMessageType('CreateAsset', (_message.Message,), dict(
  DESCRIPTOR = _CREATEASSET,
  __module__ = 'models.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateAsset)
  ))
_sym_db.RegisterMessage(CreateAsset)

ApproveAsset = _reflection.GeneratedProtocolMessageType('ApproveAsset', (_message.Message,), dict(
  DESCRIPTOR = _APPROVEASSET,
  __module__ = 'models.payload_pb2'
  # @@protoc_insertion_point(class_scope:ApproveAsset)
  ))
_sym_db.RegisterMessage(ApproveAsset)

CloseAsset = _reflection.GeneratedProtocolMessageType('CloseAsset', (_message.Message,), dict(
  DESCRIPTOR = _CLOSEASSET,
  __module__ = 'models.payload_pb2'
  # @@protoc_insertion_point(class_scope:CloseAsset)
  ))
_sym_db.RegisterMessage(CloseAsset)


# @@protoc_insertion_point(module_scope)
