version: '2'
services:
  multichain-node-1:
    ports:
     - "3000:3000"
     - "80:80"
    volumes:
     - .:/usr/app/src
    image: "hemant24/cloud9:multichain"


  multichain-node-2:
    ports:
     - "3001:3000"
     - "81:80"
    volumes:
     - .:/usr/app/src
    image: "hemant24/cloud9:multichain"